version: "3"

vars:
  CLI: "uv run shield"

tasks:

  install:
    desc: Install project dependencies
    cmds:
      - uv sync

  lint:
    desc: Run linter
    cmds:
      - uv run ruff check --fix .

  format:
    desc: Format code
    cmds:
      - uv run ruff format .

  test:
    desc: Run tests
    cmds:
      - uv run pytest

  shield:preprocess:
    desc: "Preprocess test_data.csv. Options: N=<int> (limit rows), LD=true (detect language), A=true (augment)"
    cmds:
      - "{{.CLI}} preprocess test_data.csv {{if .N}}-n {{.N}}{{end}} {{if .LD}}-ld{{end}} {{if .A}}-a{{end}}"

  shield:analyze:
    desc: Run prompt shield analysis on test_data.csv
    cmds:
      - "{{.CLI}} analyze test_data.csv"
